// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Fdv1PyJ74rc7ngyUYzFQAP52Rhr7eT0',
    appId: '1:473880402578:android:8f350f56cd47e61836644b',
    messagingSenderId: '473880402578',
    projectId: 'tunirand',
    databaseURL: 'https://tunirand-default-rtdb.firebaseio.com',
    storageBucket: 'tunirand.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWruyH9LkSrSIUKtEFKkFIHNYmtJ6KCoA',
    appId: '1:473880402578:ios:22cac2e7ce55098c36644b',
    messagingSenderId: '473880402578',
    projectId: 'tunirand',
    databaseURL: 'https://tunirand-default-rtdb.firebaseio.com',
    storageBucket: 'tunirand.appspot.com',
    iosClientId: '473880402578-tcqlcrae4aaq6721l4s790gcbvr80evo.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuniRand',
  );
}
